version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - grunt
artifacts:
  files:
    - '**/*'
  base-directory: build